# Generated by Django 5.1.4 on 2025-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayatplast', '0005_alter_contactusmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'ordering': ('-id',), 'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlər'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ('-id',), 'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='contactinfomodel',
            options={'ordering': ('-id',), 'verbose_name': 'Əlaqə məlumatı', 'verbose_name_plural': 'Əlaqə məlumatları'},
        ),
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'ordering': ('status', '-id'), 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ('-id',), 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotolar'},
        ),
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Xəbər', 'verbose_name_plural': 'Xəbərlər'},
        ),
        migrations.AlterModelOptions(
            name='newstagmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Xəbər teqi', 'verbose_name_plural': 'Xəbər teqləri'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AlterModelOptions(
            name='socialmediamodel',
            options={'ordering': ('-id',), 'verbose_name': 'Sosial media hesabı', 'verbose_name_plural': 'Sosial media hesabları'},
        ),
        migrations.AlterModelOptions(
            name='statisticsmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistikalar'},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'ordering': ('-id',), 'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='icon_name',
            field=models.TextField(verbose_name='İkon'),
        ),
    ]
