# Generated by Django 5.1.4 on 2025-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayatplast', '0006_alter_bannermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension1', models.FloatField(blank=True, null=True, verbose_name='1-ci ölçü')),
                ('dimension2', models.FloatField(blank=True, null=True, verbose_name='2-ci ölçü')),
                ('dimension3', models.FloatField(blank=True, null=True, verbose_name='3-cü ölçü')),
            ],
            options={
                'verbose_name': 'Ölçü',
                'verbose_name_plural': 'Ölçülər',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='dimension1',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='dimension2',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='dimension3',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='dimensions',
            field=models.ManyToManyField(related_name='d_products', to='mayatplast.dimensionmodel', verbose_name='Ölçü'),
        ),
    ]
