# Generated by Django 5.1.4 on 2025-02-26 14:22

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayatplast', '0007_dimensionmodel_remove_productmodel_dimension1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_dimensions',
            field=models.ManyToManyField(related_name='d_products', to='mayatplast.dimensionmodel', verbose_name='Ölçü'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='dimensions',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Ölçülər'),
        ),
    ]
